const data = [
  {
    id: '1',
    name: 'Canon 6D Mark 2',
    price: 1425,
    image: '/images/Canon 6D Mark 2.png',
    bookmarked: false,
    description: 'blabala',
    category: 'body',
  },
  {
    id: '2',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blabla',
    category: 'body',
  },
  {
    id: '3',
    name: 'FujiFilm X-T4',
    price: 2299,
    image: '/images/FujiFilm X-T4.png .png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '4',
    name: 'Nikon Z7',
    price: 3969,
    image:
      'https://media.foto-erhardt.de/images/product_images/popup_images/693/nikon-z7-ii-gehause-nikkor-z-24-120mm-f4-s-163705870169370304.jpg',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },

  {
    id: '5',
    name: 'a7c',
    price: 1199,
    image: '/images/a7c.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },

  {
    id: '6',
    name: 'NIKON D850',
    price: 2999,
    image: '/images/NIKON D850.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '7',
    name: 'a7II',
    price: 1199,
    image: '/images/Sony a7II.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '8',
    name: 'Lumix GH5',
    price: 1599,
    image: '/images/Lumix GH5.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '9',
    name: 'Nikon 50mm f/1.8G',
    price: 239,
    image: '/images/Nikon 50mm.png',
    bookmarked: false,
    description:
      'The Nikon 50mm f/1.8G is far and away my top pick for beginners who want to get into portrait photography without spending a lot of money',
    category: 'lens',
    slider: '/images/slider1.png /images/slider2.png /images/slider3.png',
  },
  {
    id: '10',
    name: 'Canon EF 85mm f/1.4L IS USM',
    price: 1069,
    image: '/images/Canon EF 85mm f:1.4L IS USM.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '11',
    name: 'Sigma 40mm f/1.4 DG HSM | Art',
    price: 749,
    image: '/images/Sigma 40mm f:1.4 DG HSM | Art.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '12',
    name: 'Canon EF 50mm f/1.2L USM',
    price: 1499,
    image: '/images/Canon EF 50mm f:1.2L USM.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '13',
    name: 'Sony FE 85mm f/1.4 GM',
    price: 1399,
    image: '/images/Sony FE 85mm f:1.4 G.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
];
export default data;
