const data = [
  {
    id: '1',
    name: 'Canon EOS 5D Mark IV',
    price: 1597,
    image: '/images/Canon eos 5d mark iv.png',
    bookmarked: false,
    description: 'Lorem Ipsum',
    category: 'body',
  },

  {
    id: '2',
    name: 'Canon 6D Mark 2',
    price: 1425,
    image: '/images/Canon 6D Mark 2.png',
    bookmarked: false,
    description: 'blabala',
    category: 'body',
  },
  {
    id: '3',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blabla',
    category: 'body',
  },
  {
    id: '4',
    name: 'FujiFilm X-T4',
    price: 2299,
    image: '/images/FujiFilm X-T4.png .png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '5',
    name: 'Nikon Z7',
    price: 3969,
    image:
      'https://media.foto-erhardt.de/images/product_images/popup_images/693/nikon-z7-ii-gehause-nikkor-z-24-120mm-f4-s-163705870169370304.jpg',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },

  {
    id: '6',
    name: 'a7c',
    price: 1199,
    image: '/images/a7c.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '7',
    name: 'Olympus E-M5 MARK III',
    price: 1399,
    image: '/images/Olympus E-M5 MARK III.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '8',
    name: 'NIKON D850',
    price: 2999,
    image: '/images/NIKON D850.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'body',
  },
  {
    id: '9',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '10',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '11',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '12',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '13',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '14',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '15',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '16',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '17',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '18',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '19',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '20',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
  {
    id: '21',
    name: 'a7000',
    price: 2799,
    image: '/images/a7000.png',
    bookmarked: false,
    description: 'blablabal',
    category: 'lens',
  },
];
export default data;
